"""Módulo 0002_delete_reserva."""

from django.db import migrations

# Generated by Django 5.2.3 on 2025-06-18 23:19

class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
